=== qenfay/know-dot-edu-dot-pk/UI_redesigned/XML/account.dtd
<!ELEMENT account (name, username, password)>
<!ATTLIST account type (teacher | student) #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>

=== qenfay/know-dot-edu-dot-pk/XML/account.xml
<?xml version = "1.0"?>
<!DOCTYPE account SYSTEM "account.dtd">
<account type = "learner">
	<name>John Wick</name>
	<username>johnwitch90</username>
	<password>password</password>
</account>

<account type = "teacher">
	<name>Talaal Bajwa</name>
	<username>tb.bscs18seecs</username>
	<password>nust123</password>
</account>
